// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PlaylistInitParameters struct {

	// The description of the resulting playlist
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the resulting playlist
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether the playlist can be accessed publically
	Public *bool `json:"public,omitempty" tf:"public,omitempty"`

	// A set of tracks for the playlist to contain
	Tracks []*string `json:"tracks,omitempty" tf:"tracks,omitempty"`
}

type PlaylistObservation struct {

	// The description of the resulting playlist
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the resulting playlist
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether the playlist can be accessed publically
	Public *bool `json:"public,omitempty" tf:"public,omitempty"`

	SnapshotID *string `json:"snapshotId,omitempty" tf:"snapshot_id,omitempty"`

	// A set of tracks for the playlist to contain
	Tracks []*string `json:"tracks,omitempty" tf:"tracks,omitempty"`
}

type PlaylistParameters struct {

	// The description of the resulting playlist
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the resulting playlist
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether the playlist can be accessed publically
	// +kubebuilder:validation:Optional
	Public *bool `json:"public,omitempty" tf:"public,omitempty"`

	// A set of tracks for the playlist to contain
	// +kubebuilder:validation:Optional
	Tracks []*string `json:"tracks,omitempty" tf:"tracks,omitempty"`
}

// PlaylistSpec defines the desired state of Playlist
type PlaylistSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PlaylistParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PlaylistInitParameters `json:"initProvider,omitempty"`
}

// PlaylistStatus defines the observed state of Playlist.
type PlaylistStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PlaylistObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Playlist is the Schema for the Playlists API. Resource to manage a spotify playlist.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,spotify}
type Playlist struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.tracks) || (has(self.initProvider) && has(self.initProvider.tracks))",message="spec.forProvider.tracks is a required parameter"
	Spec   PlaylistSpec   `json:"spec"`
	Status PlaylistStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PlaylistList contains a list of Playlists
type PlaylistList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Playlist `json:"items"`
}

// Repository type metadata.
var (
	Playlist_Kind             = "Playlist"
	Playlist_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Playlist_Kind}.String()
	Playlist_KindAPIVersion   = Playlist_Kind + "." + CRDGroupVersion.String()
	Playlist_GroupVersionKind = CRDGroupVersion.WithKind(Playlist_Kind)
)

func init() {
	SchemeBuilder.Register(&Playlist{}, &PlaylistList{})
}
