name: conradludgate/spotify
resources:
    spotify_library:
        subCategory: ""
        name: spotify_library
        title: spotify_library Resource - terraform-provider-spotify
        examples:
            - name: my_library
              manifest: |-
                {
                  "tracks": [
                    "${data.spotify_track.overkill.id}",
                    "${data.spotify_track.blackwater.id}",
                    "${data.spotify_track.snowblind.id}"
                  ]
                }
        argumentDocs: {}
        importStatements: []
    spotify_library_albums:
        subCategory: ""
        name: spotify_library_albums
        title: spotify_library_albums Resource - terraform-provider-spotify
        examples:
            - name: my_album
              manifest: |-
                {
                  "albums": [
                    "${data.spotify_album.only_in_dreams.id}",
                    "${data.spotify_album.the_promised_land.id}"
                  ]
                }
        argumentDocs: {}
        importStatements: []
    spotify_playlist:
        subCategory: ""
        description: Resource to manage a spotify playlist.
        name: spotify_playlist
        title: spotify_playlist Resource - terraform-provider-spotify
        examples:
            - name: playlist
              manifest: |-
                {
                  "description": "My playlist is so awesome",
                  "name": "My playlist",
                  "public": false,
                  "tracks": [
                    "${data.spotify_track.overkill.id}",
                    "${data.spotify_track.blackwater.id}",
                    "${data.spotify_track.snowblind.id}"
                  ]
                }
        argumentDocs: {}
        importStatements:
            - |-
              # Using the playlist ID
              # https://open.spotify.com/playlist/37i9dQZF1DWVs8I62NcHks (a playlist share link)
              #                                   ^^^^^^^^^^^^^^^^^^^^^^
              terraform import spotify_playlist.example 37i9dQZF1DWVs8I62NcHks
