apiVersion: playlist.spotify.crossplane.io/v1alpha1
kind: Playlist
metadata:
  annotations:
    meta.upbound.io/example-id: playlist/v1alpha1/playlist
  labels:
    testing.upbound.io/example-name: playlist
  name: playlist
spec:
  forProvider:
    description: My playlist is so awesome
    name: My playlist
    public: false
    tracks:
    - ${data.spotify_track.overkill.id}
    - ${data.spotify_track.blackwater.id}
    - ${data.spotify_track.snowblind.id}
